### ISSUE TITLE
Error on install on Pi.

### ISSUE THREAD

**Issue by steveyboy** [fcsonline/node-telescope-server#2]
Hi

When I try to install it on a pi I  get the following error.

npm http GET https://registry.npmjs.org/node-telescope-server
npm http 304 https://registry.npmjs.org/node-telescope-server
npm http GET https://registry.npmjs.org/node-telescope-server/-/node-telescope-server-0.0.4.tgz
npm http 200 https://registry.npmjs.org/node-telescope-server/-/node-telescope-server-0.0.4.tgz
npm ERR! Error: shasum check failed for /root/tmp/npm-6103-P4GIM2p0/1394727661574-0.11756702442653477/tmp.tgz
npm ERR! Expected: 127a9dabd7000d826fd5e0ff771645b1c4e17041
npm ERR! Actual:   492090033faad910dde7893e62726311b8325fe7
npm ERR! From:     https://registry.npmjs.org/node-telescope-server/-/node-telescope-server-0.0.4.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.10.25+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-telescope-server" "-g"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

My All my current nodejs and npm packages have later versions than you show in the help file.

see

pi@raspberrypi ~ $ npm -v
1.1.4
pi@raspberrypi ~ $ node -v
v0.10.26

Any help would be appreciated .

Steve

**Comment by fcsonline** [comment]
It looks like an old npm issue. Closing.
