### ISSUE TITLE
Error installing "...shasum check failed for.."

### ISSUE THREAD

**Issue by rodolfoprado** [fcsonline/node-telescope-server#3]
Hi,
I'm trying to install node-telescope but i'm having this problem: 
can you help me?

pi@raspberrypi ~ $ npm -v
1.4.14
pi@raspberrypi ~ $ node -v
v0.10.29
---------------
pi@raspberrypi ~ $ sudo npm install node-telescope-server -g
npm ERR! Error: shasum check failed for /root/tmp/npm-2405-ZWSm_yWV/registry.npmjs.org/node-telescope-server/-/node-telescope-server-0.0.4.tgz
npm ERR! Expected: 127a9dabd7000d826fd5e0ff771645b1c4e17041
npm ERR! Actual:   492090033faad910dde7893e62726311b8325fe7
npm ERR! From:     https://registry.npmjs.org/node-telescope-server/-/node-telescope-server-0.0.4.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:929:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.12.22+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-telescope-server" "-g"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by fcsonline** [comment]
It looks like a npm old issue. Closing.
